name: thesis
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python>=3.7
  - pytorch=1.9.0
  - networkx
  - matplotlib
  - cudatoolkit=11.1
  - torchvision
  - torchaudio
  - tensorboard
